# Generated by Django 5.2.17 on 2026-09-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctoravailability'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='doctoravailability',
            constraint=models.UniqueConstraint(fields=('doctor', 'day', 'start_time', 'end_time'), name='unique_doctor_availability'),
        ),
    ]
